{% set name = "suitcase-specfile" %}
{% set version = "0.2.1" %}
{% set sha256 = "dbced43d8531551541537bc6029702f76e69afcd01fbf356076411f67f3d30ce" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python
    - pip
  run:
    - python
    - event-model >=1.8.0
    - jinja2
    - suitcase-utils >=0.1.0

test:
  imports:
    - suitcase.specfile
    - suitcase.specfile.tests

about:
  home: https://blueskyproject.io/suitcase
  license: BSD (3-clause)
  license_family: BSD
  license_file: LICENSE
  summary: Export bluesky documents to specfile
  doc_url: https://blueskyproject.io/suitcase
  dev_url: https://github.com/bluesky/suitcase-specfile
